from colorama import Fore

URL_ENDPOINT = "https://srevinsaju.me/get-appimage/{}/core.json"
URL_SHOWCASE = "https://srevinsaju.me/get-appimage/{}/"
YES_RESPONSES = ("yes", "y", "yea", "yup", "ye")

ZAP_PATH_RC_PATCH = \
    """# ========================
# auto generated by Zap AppImage Package Manager: do not remove!
# Add the path to ZAP bin to PATH environment variable
export ZAP_PATH={path_to_bin}
export PATH=$PATH:$ZAP_PATH
# ========================"""

COMMAND_WRAPPER = \
    """#!/bin/env sh
{path_to_appimage} "$@" """

COLORS = {
    'g': Fore.GREEN,
    'rst': Fore.RESET,
    'y': Fore.YELLOW,
    'r': Fore.RED
}
